---

user_groups__fedora_workstations:
  - libvirt
  - dialout

#copr, third party repos
copr_list__fedora_workstatsions:
  - mroche/cloud-native-utilities # helm,knative-client,pack,packer,tektoncd-cli,terraform
  - zeno/scrcpy
  - kylegospo/webapp-manager
  #- felfert/gitea
  #- varlad/zellij    #A terminal workspace with batteries included. (tmux alternative)
  - getpagespeed/wrk #modern HTTP benchmarking tool
  #- pgdev/ghostty
  - trixieua/morewaita-icon-theme

# remove copr repos
copr_absent_list__fedora_workstations:
  - luya/xournalpp # latest xournal++
  - varlad/helix

#third party repos
other_repos_list__fedora_workstations: []
  #- https://fedorapeople.org/groups/virt/virtio-win/virtio-win.repo
  #- https://download.docker.com/linux/fedora/docker-ce.repo

#third party repos and packages
direct_package_list__fedora_workstations:
  - "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version }}.noarch.rpm"
  #- "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_version }}.noarch.rpm"
  #- "http://repo.yandex.ru/yandex-disk/yandex-disk-latest.x86_64.rpm"    #yandex-disk repository
  #- "https://storage.googleapis.com/minikube/releases/latest/minikube-latest.x86_64.rpm"

#third party repos and packages
prerequisite_packages_list__fedora_workstations:
  - fedora-workstation-repositories

# enable repo if needed
setenabled_repo_list__fedora_workstations: []
  #- google-chrome

#NOTE: already defined in group_vars/all.yml, re-define here to override
#yum_repos_mirror:
#yum_repos_tweaks:

package_list__fedora_workstations:
  # ----- termiinal -----
  - tilix          # main terminal
  - tilix-nautilus
  #- terminator
  #- ghostty
  - cosmic-term    # next terminal (?)
  - powerline
  - tmux
  - tmux-powerline
  - screen
  - mc
  # ----- editors -----
  - vim-enhanced
  - vim-nerdtree
  - awesome-vim-colorschemes
  - vim-jedi
  - vim-go
  #- golang-x-tools-gopls #for vim-go
  - vim-ansible
  - vim-powerline
  - micro # a modern and intuitive terminal-based text editor
  - helix # text editor. from varlad/helix copr repo
  # ----- desktop -----
  #- google-chrome-stable  # from google-chrome repo (fedora-workstation-repositories pkg)
  - dconf-editor
  - gnome-tweaks
  - gnome-themes-extra # adwaita-dark for legacy applications
  - gnome-extensions-app
  - gnome-shell-extension-appindicator
  - gnome-shell-extension-apps-menu
  - gnome-shell-extension-argos
  - gnome-shell-extension-background-logo
  - gnome-shell-extension-blur-my-shell
  - gnome-shell-extension-dash-to-dock
  - gnome-shell-extension-just-perfection
  - gnome-shell-extension-just-perfection
  - gnome-shell-extension-launch-new-instance
  - gnome-shell-extension-openweather
  - gnome-shell-extension-places-menu
  #- gnome-shell-extension-pop-shell
  - gnome-shell-extension-pomodoro
  - gnome-shell-extension-screen-autorotate
  - gnome-shell-extension-system-monitor-applet
  - gnome-shell-extension-user-theme
  - gnome-shell-extension-window-list
  - gnome-shell-extension-workspace-indicator
  - libdbusmenu # for dash-to-dock
  - virt-manager
  - virt-viewer
  - virt-what
  - libvirt-client
  - minder
  - morewaita-icon-theme
  - scrcpy #from zeno/scrcpy copr
  - showtime  # Modern video player built using GTK4
  - wl-clipboard
  - xournalpp # from luya/xournalpp copr repo, latest xournal++
  - transmission
  - clapper # A GNOME media player (GJS,GTK4).  (installed for live wallpaper best performance)
  - webapp-manager # from kylegospo/webapp-manage copr
  - helvum #patchbay for pipewire
  - keepassxc
  #- thunderbird   # outdated version
  # ----- tools -----
  - apg
  - autofs
  - bat # A cat(1) clone with wings. (Rust)  --- in all group
  - bcc
  - bind-utils
  - bpftrace
  - bpftool
  - cargo
  - clide # colorize ASCII text
  - cockpit
  - cockpit-files
  - cockpit-machines
  - cockpit-podman
  - cockpit-selinux
  - colorized-logs
  #- cockpit-pcp
  #- containerd.io # docker-ce
  - crudini # A utility for manipulating ini files
  - curl
  #- distrobox
  - dnf-utils
  - dnstop
  #- docker-ce # docker-ce
  #- docker-ce-cli # docker-ce
  #- docker-compose-plugin # docker-ce
  - eza
  - fatrace
  #- ffmpeg
  - fuse-sshfs
  - fzf  #A command-line fuzzy finder  --- in all group
  - gcc
  - git
  - git-extras
  #- git-delta
  - gitg #git gui
  - golang
  #- go-task
  #- golang-github-docker-slim # docker-slim tool
  #- grafana
  - grpcurl
  - hadolint # Dockerfile linter
  - helm
  - hping3 #TCP/IP stack auditing
  - htop
  - hwloc-gui #lstopo
  - inotify-tools
  - java-21-openjdk
  - java-21-openjdk-headless
  - jq
  - knock
  - kubernetes-client
  #- kubectl
  - lm_sensors
  - maven
  - meld #diff gui
  - mtr
  - nethogs
  - nmap
  - nmap-ncat
  - openssl
  - opentofu    # terraform alt.
  - parallel
  - perf
  - perl-Image-ExifTool
  - pipx #Install and Run Python Applications in Isolated Environments
  - podman
  - podman-docker # Emulate Docker CLI using podman
  #- podman-compose
  - powertop
  - pre-commit
  - progress # Linux tool to show progress for cp, mv, dd, ... (formerly known as cv)
  - pv # monitor the progress of data through a pipe
  - pylint
  - python-virtualenv
  - python-xdot # graphviz's dot viewer
  - python3-aiohttp # dependency (ansible-rulebook, tftui)
  - python3-bashate   # automated style checker for bash scripts
  - python3-devel
  - python3-pip
  - python3-psutil
  - python3-pytest-testinfra
  - python3-requests
  #- python3-testinfra
  #- ranger # console file manager
  - rdiff-backup
  - rust
  #- scalpel # file recovery / undo delete
  - ShellCheck # shell script static analysis tool (bash linter)
  - skopeo
  - sshuttle
  - sysstat
  - tango-icon-theme
  - the_silver_searcher
  #- terraform # from mroche/cloud-native-utilities copr repo  # repl. by opentofu
  - toolbox
  - tuned
  #- virtio-win
  #- waydroid         # Waydroid uses a container-based approach to boot a full Android system on a regular GNU/Linux system
  - wget
  - wireguard-tools
  - wrk #modern HTTP benchmarking tool (copr repo)
  - yamllint
  - papers   #document viewer

package_absent_list__fedora_workstations:
  #  - nano
  - firefox-wayland #not needed since firefox version 121
  - python3-pytelegrambotapi

# upgrade packages
packages_upgrade: false
packages_upgrade_all: false
##packages_upgrade_security_only: false

flatpak_repos__fedora_workstations:
  - https://flathub.org/repo/flathub.flatpakrepo

flatpak_packages__fedora_workstations:
  - com.google.Chrome
  - com.github.tchx84.Flatseal
  - com.github.johnfactotum.Foliate
  - org.gnome.Geary
  - org.gimp.GIMP
  - org.inkscape.Inkscape
  - org.kde.kdenlive
  #- us.zoom.Zoom
  - com.obsproject.Studio
  #- com.spotify.Client
  #- io.atom.Atom
  - com.jgraph.drawio.desktop
  #- com.valvesoftware.Steam
  #- com.github.gi_lom.dialect
  #- app.drey.Dialect
  - org.videolan.VLC
  #- org.zotero.Zotero
  #- com.getpostman.Postman
  #- com.transmissionbt.Transmission   # have it in package_list
  #- net.xmind.XMind8
  #- net.xmind.ZEN
  - net.xmind.XMind
  #- org.freeplane.App
  - io.gitlab.news_flash.NewsFlash
  #- com.github.xournalpp.xournalpp
  #- com.getferdi.Ferdi
  #- com.skype.Client
  #- org.signal.Signal
  - org.telegram.desktop
  #- com.viber.Viber
  #- im.riot.Riot
  #- org.jitsi.jitsi-meet
  #- com.google.AndroidStudio
  - net.cozic.joplin_desktop
  - de.haeckerfelix.Fragments # bittorrent client
  - org.libreoffice.LibreOffice
  # - com.belmoussaoui.Authenticator
  - re.sonny.Tangram
  - com.rafaelmardojai.Blanket
  #- com.slack.Slack
  - org.cockpit_project.CockpitClient
  - com.github.jeromerobert.pdfarranger
  - rest.insomnia.Insomnia # Open Source API Client (Postman alternative)
  - com.github.marhkb.Pods
  #- net.nokyan.Resources
  #- org.kiwix.desktop          # offline reader (download wikipedia)
  #- app.organicmaps.desktop    # offline maps - Hike, Bike, Drive Offline
  - dev.zed.Zed
  - io.dbeaver.DBeaverCommunity
  - io.dbeaver.DBeaverCommunity.Client.pgsql
  - io.github.jeffshee.Hidamari  # Video wallpaper for Linux
  #- org.gnome.Chess   # classic chess game
  #- org.kde.kigo      # classic go game
  - cc.arduino.IDE2
  - com.google.AndroidStudio
  #- com.gexperts.Tilix    # package instead
  #- com.rustdesk.RustDesk # remote desktop / assistant
  #- org.gnome.Papers

# pip (no venv)
pip_requirements: "~/.pip.requirements.txt"
# additional pip packages
pip_packages__fedora_workstations:
  - powerline-k8s
  #- terminalteixteffects #tte (just for fun)

# venv pip
# to create venvs and install {{ python_venv_dir }}/<virtualenv>.requirements.txt
python_venv_dir: "~/python-venv"
python_version: "3.13"
# additional pip packages for venvs
pip_default_venv: "py"
pip_venv_packages__fedora_workstations: {}
#  default:   # pip_default_venv
#    - pip_package
#  venv_name:
#    - pip_package

pipx_packages__fedora_workstations:
  #ansible:
  #  - argcomplete
  #  - requests
  #  - kubernetes
  #  - pip-system-certs
  #ansible-runner:
  #  - ansible-runner-http
  #ansible-lint:
  #ansible-rulebook:
  yt-dlp:
  #youtube-dl:
  yq:
  awxkit:
  tftui: # Terraform textual UI
  #bashate:   # automated style checker for bash scripts

cargo_packages__fedora_workstations:
  - du-dust
  #- eza
  - tealdeer   #tldr
  #- httpie
  #- xh
  #- git-delta
  #- fd-find  # alternative to find                     #already in packages_list
  #- apkeep    # download APK packages (apkpure, googleplay)
  #- pup       # Command-line HTML parsing tool
  #- bat       # A cat(1) clone with wings. (Rust)      # already in package_list
  - tomato-toml # crudini-like tool but for toml
  #- coreutils
  - gitlab-ci-ls  # for zed's plugin

go_packages__fedora_workstations:
  #- github.com/antonmedv/llama   # terminal file manager
  #- github.com/mikefarah/yq      # notice pip yq package
  - github.com/go-task/task/v3/cmd/task
  #- github.com/ericchiang/pup    # html parser
  #- golang.stackrox.io/kube-linter/cmd/kube-linter
  #- github.com/gcla/termshark/v2/cmd/termshark     #A terminal user-interface for tshark
  - fortio.org/fortio #load testing tool
  - github.com/kubecolor/kubecolor

# TODO: add requirements.yml file support
ansible_galaxy_venv: "ansible"
ansible_galaxy_collections__fedora_workstations:
#  - community.general
  - ansible.eda
#  - kubernetes.core

# dash/dock panel favorite apps ($ dconf read /org/gnome/shell/favorite-apps)
# dconf read /org/gnome/shell/favorite-apps
# in case there are other favorite_apps__ variables the __NN__ suffix controlls position, i.e.
# __00__ -  to be on the left side (start of the list)
# __99__ -  to be on the right side (end of the list)
favorite_apps__50__fedora_workstations:
  - com.gexperts.Tilix.desktop
  #- org.gnome.Ptyxis.desktop
  #- terminator.desktop
  #- com.mitchellh.ghostty.desktop
  - dev.zed.Zed.desktop
  - net.cozic.joplin_desktop.desktop
  #- firefox-wayland.desktop
  - net.thunderbird.Thunderbird.desktop
  - org.mozilla.firefox.desktop
  #- org.gnome.Geary.desktop
  #- org.gnome.Calendar.desktop
  - io.gitlab.news_flash.NewsFlash.desktop
  - org.telegram.desktop.desktop
  #- google-chrome.desktop
  #- com.google.Chrome.desktop
  #- com.github.xournalpp.xournalpp.desktop
  #- net.xmind.XMind.desktop
  #- org.freeplane.App.desktop
  - com.github.phase1geo.minder.desktop
  #- re.sonny.Tangram.desktop
  #- com.getferdi.Ferdi.desktop
  #- com.slack.Slack.desktop
  - org.gnome.Nautilus.desktop
  #- org.gnome.TextEditor.desktop
  #- org.gnome.gedit.desktop
  - org.gnome.Calculator.desktop
  - org.cockpit_project.CockpitClient.desktop
  - remote-viewer.desktop
  - virt-manager.desktop
  #- org.cockpit_project.CockpitClient.desktop
  #- org.gnome.Calendar.desktop
  - scrcpy.desktop
  #- org.gnome.gitg.desktop
  #- org.gnome.Meld.desktop
  #- rest.insomnia.Insomnia.desktop
  - com.rafaelmardojai.Blanket.desktop
  - org.keepassxc.KeePassXC.desktop
  - WebApp-CoridorCamera0001.desktop

# dconf dump files might be used as well (see README)
dconf_settings__fedora_workstations:
  "/org/gnome/shell/favorite-apps": "{{ favorite_apps }}"
  "/org/gnome/desktop/a11y/always-show-universal-access-status": "false"
  #  "/org/gnome/desktop/background/picture-uri": "'file:///home/username/Pictures/wallpapers/wallpaper.jpg'"
  "/org/gnome/desktop/interface/icon-theme": "'MoreWaita'"
  "/org/gnome/desktop/interface/gtk-theme": "'Adwaita-dark'"
  "/org/gnome/desktop/interface/clock-show-weekday": "true"
  "/org/gnome/desktop/interface/show-battery-percentage": "true"
  "/org/gnome/desktop/peripherals/mouse/natural-scroll": "true"
  "/org/gnome/desktop/peripherals/touchpad/natural-scroll": "true"
  "/org/gnome/desktop/peripherals/touchpad/tap-to-click": "true"
  "/org/gnome/desktop/wm/preferences/focus-mode": "'sloppy'"
  "/org/gnome/desktop/wm/preferences/auto-raise": "true"
  "/org/gtk/Settings/FileChooser/show-hidden": "true"
  "/org/gnome/nautilus/preferences/show-delete-permanently": "true"
  "/org/gnome/nautilus/preferences/show-create-link": "true"
  "/org/gtk/Settings/FileChooser/sort-directories-first": "true"
  #  "/org/gnome/nautilus/icon-view/default-zoom-level": "'small'"
  "/org/gnome/nautilus/icon-view/default-zoom-level": "'small-plus'"
  "/com/gexperts/Tilix/Settingsterminal-title-show-when-single": "false"
  "/com/gexperts/Tilix/Settingsterminal-title-style": "'small'"
  "/com/gexperts/Tilix/Settingstheme-variant": "'dark'"
  "/com/gexperts/Tilix/Settingsuse-tabs": "true"
  #  "/com/gexperts/Tilix/quake-alignment": "'left'"
  #  "/com/gexperts/Tilix/quake-height-percent": "40"
  #  "/com/gexperts/Tilix/quake-width-percent": "50"
  #  "/com/gexperts/Tilix/quake-hide-headerbar": "true"
  #  "/com/gexperts/Tilix/quake-hide-lose-focus": "true"
  #  "/org/gnome/gedit/preferences/editor/scheme": "'oblivion'"
  "/org/gnome/shell/extensions/dash-to-dock/show-mounts": "false"
  "/org/gnome/shell/extensions/dash-to-dock/force-straight-corner": "false"
  "/org/gnome/shell/extensions/dash-to-dock/dash-max-icon-size": "32"
  #  "/org/gnome/shell/extensions/dash-to-dock/intellihide-mode": "'FOCUS_APPLICATION_WINDOWS'"
  "/org/gnome/shell/extensions/dash-to-dock/intellihide-mode": "'ALL_WINDOWS'"
  "/org/gnome/shell/extensions/dash-to-dock/show-trash": "false"
  "/org/gnome/shell/extensions/dash-to-dock/apply-custom-theme": "true"
  "/org/gnome/shell/extensions/just-perfection/dash-icon-size": "32"
  "/org/gnome/shell/extensions/just-perfection/events-button": "false"
  "/org/gnome/shell/extensions/just-perfection/workspace-switcher-should-show": "true"
  "/org/gnome/shell/extensions/just-perfection/workspace-switcher-size": "15"
  "/org/gnome/shell/extensions/just-perfection/workspace-wrap-around": "true"
  "/org/gnome/shell/extensions/just-perfection/world-clock": "false"
  #"/org/gnome/mutter/check-alive-timeout": "0"
  "/org/gnome/mutter/check-alive-timeout": "60000"
