---
fedora_version: 41

files_repos:
  - {
      repo: "git@github.com:goloshubov/fconfig_files.git",
      localpath: "~/git/github/fconfig_files",
    }
  - {
      repo: "git@github.com:goloshubov/fconfig_files_private.git",
      localpath: "~/git/github/fconfig_files_private",
    }

dnf_proxy_protocol: http
dnf_proxy_host: 192.168.35.1
dnf_proxy_port: 3128

# original repos settings
yum_repos_tweaks_original:
  - {
      path: "/etc/yum.repos.d/fedora.repo",
      section: "fedora",
      option: "metalink",
      value: "https://mirrors.fedoraproject.org/metalink?repo=fedora-$releasever&arch=$basearch",
    }
  - {
      path: "/etc/yum.repos.d/fedora-updates.repo",
      section: "updates",
      option: "metalink",
      value: "https://mirrors.fedoraproject.org/metalink?repo=updates-released-f$releasever&arch=$basearch",
    }
  #  - { path: "/etc/yum.repos.d/fedora-modular.repo",
  #      section: "fedora-modular",
  #      option: "metalink",
  #      value: "https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-$releasever&arch=$basearch" }
  #  - { path: "/etc/yum.repos.d/fedora-updates-modular.repo",
  #      section: "updates-modular",
  #      option: "metalink",
  #      value: "https://mirrors.fedoraproject.org/metalink?repo=updates-released-modular-f$releasever&arch=$basearch" }
  - {
      path: "/etc/yum.repos.d/rpmfusion-free.repo",
      section: "rpmfusion-free",
      option: "metalink",
      value: "https://mirrors.rpmfusion.org/metalink?repo=free-fedora-$releasever&arch=$basearch",
    }
  - {
      path: "/etc/yum.repos.d/rpmfusion-free-updates.repo",
      section: "rpmfusion-free-updates",
      option: "metalink",
      value: "https://mirrors.rpmfusion.org/metalink?repo=free-fedora-updates-released-$releasever&arch=$basearch",
    }

# custom repos settings (yandex mirror)
yum_repos_mirror: "http://mirror.yandex.ru"
yum_repos_tweaks_mirror:
  - {
      path: "/etc/yum.repos.d/fedora.repo",
      section: "fedora",
      option: "baseurl",
      value: "{{ yum_repos_mirror }}/fedora/linux/releases/$releasever/Everything/$basearch/os/",
    }
  - {
      path: "/etc/yum.repos.d/fedora-updates.repo",
      section: "updates",
      option: "baseurl",
      value: "{{ yum_repos_mirror }}/fedora/linux/updates/$releasever/Everything/$basearch/",
    }
  #  - { path: "/etc/yum.repos.d/fedora-modular.repo",
  #      section: "fedora-modular",
  #      option: "baseurl",
  #      value: "{{ yum_repos_mirror }}/fedora/linux/releases/$releasever/Modular/$basearch/os/" }
  #  - { path: "/etc/yum.repos.d/fedora-updates-modular.repo",
  #      section: "updates-modular",
  #      option: "baseurl",
  #      value: "{{ yum_repos_mirror }}/fedora/linux/updates/$releasever/Modular/$basearch/" }
  - {
      path: "/etc/yum.repos.d/rpmfusion-free.repo",
      section: "rpmfusion-free",
      option: "baseurl",
      value: "{{ yum_repos_mirror }}/fedora/rpmfusion/free/fedora/releases/$releasever/Everything/$basearch/os/",
    }
  - {
      path: "/etc/yum.repos.d/rpmfusion-free-updates.repo",
      section: "rpmfusion-free-updates",
      option: "baseurl",
      value: "{{ yum_repos_mirror }}/fedora/rpmfusion/free/fedora/updates/$releasever/$basearch/",
    }

yum_repos_tweaks: "{{ yum_repos_tweaks_original }}"

#TODO:clean, deduplicate
# common packages for all groups
package_list__fedora:
  - nmap-ncat
  - bind-utils
  - rsync
  - tmux
  #  - screen
  - git
  - vim-enhanced
  - vim-nerdtree
  - awesome-vim-colorschemes
  - curl
  - wget
  - htop
  - powerline
  - tmux-powerline
  - vim-powerline
  - lm_sensors
  - python3-psutil
  - tuned
  - powertop
  - apg
  - parallel
  #  - exa
  - dnf-utils
  - golang
  - rust
  - cargo
  - jq
  - mtr
  - openssl
  - perf
  - bpftrace
  - bcc
  - sysstat
  - inotify-tools
  #  - nethogs
  - dnstop
  #  - the_silver_searcher
  #  - rdiff-backup
  - python3-pip
  #- python3-pytelegrambotapi
  - cockpit
  #  - cockpit-podman
  #  - cockpit-machines
  #  - cockpit-pcp
  #  - cockpit-selinux
  #  - ranger      # console file manager
  - crudini # A utility for manipulating ini files
  - pv # monitor the progress of data through a pipe
  - progress # Linux tool to show progress for cp, mv, dd, ... (formerly known as cv)
  #  - bat       # A cat(1) clone with wings. (Rust)
  #- go-task
  - colorized-logs
  #  - clide  # colorize ASCII text
  - smartmontools
#  - stunnel
#  - chisel  # fast TCP/UDP tunnel, transported over HTTP, secured via SSH
