---
fedora_version: 42

# dotfiles and configs repos
files_repos:
  - {
      repo: "git@github.com:goloshubov/fconfig_files.git",
      localpath: "~/git/github/fconfig_files",
    }
  - {
      repo: "git@github.com:goloshubov/fconfig_files_private.git",
      localpath: "~/git/github/fconfig_files_private",
    }

dnf_proxy_protocol: http
dnf_proxy_host: 192.168.35.1
dnf_proxy_port: 3128

# original repos settings
yum_repos_tweaks_original:
  - {
      path: "/etc/yum.repos.d/fedora.repo",
      section: "fedora",
      option: "metalink",
      value: "https://mirrors.fedoraproject.org/metalink?repo=fedora-$releasever&arch=$basearch",
    }
  - {
      path: "/etc/yum.repos.d/fedora-updates.repo",
      section: "updates",
      option: "metalink",
      value: "https://mirrors.fedoraproject.org/metalink?repo=updates-released-f$releasever&arch=$basearch",
    }
  #  - { path: "/etc/yum.repos.d/fedora-modular.repo",
  #      section: "fedora-modular",
  #      option: "metalink",
  #      value: "https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-$releasever&arch=$basearch" }
  #  - { path: "/etc/yum.repos.d/fedora-updates-modular.repo",
  #      section: "updates-modular",
  #      option: "metalink",
  #      value: "https://mirrors.fedoraproject.org/metalink?repo=updates-released-modular-f$releasever&arch=$basearch" }
  - {
      path: "/etc/yum.repos.d/rpmfusion-free.repo",
      section: "rpmfusion-free",
      option: "metalink",
      value: "https://mirrors.rpmfusion.org/metalink?repo=free-fedora-$releasever&arch=$basearch",
    }
  - {
      path: "/etc/yum.repos.d/rpmfusion-free-updates.repo",
      section: "rpmfusion-free-updates",
      option: "metalink",
      value: "https://mirrors.rpmfusion.org/metalink?repo=free-fedora-updates-released-$releasever&arch=$basearch",
    }

# custom repos settings (yandex mirror)
yum_repos_mirror: "http://mirror.yandex.ru"
yum_repos_tweaks_mirror:
  - {
      path: "/etc/yum.repos.d/fedora.repo",
      section: "fedora",
      option: "baseurl",
      value: "{{ yum_repos_mirror }}/fedora/linux/releases/$releasever/Everything/$basearch/os/",
    }
  - {
      path: "/etc/yum.repos.d/fedora-updates.repo",
      section: "updates",
      option: "baseurl",
      value: "{{ yum_repos_mirror }}/fedora/linux/updates/$releasever/Everything/$basearch/",
    }
  #  - { path: "/etc/yum.repos.d/fedora-modular.repo",
  #      section: "fedora-modular",
  #      option: "baseurl",
  #      value: "{{ yum_repos_mirror }}/fedora/linux/releases/$releasever/Modular/$basearch/os/" }
  #  - { path: "/etc/yum.repos.d/fedora-updates-modular.repo",
  #      section: "updates-modular",
  #      option: "baseurl",
  #      value: "{{ yum_repos_mirror }}/fedora/linux/updates/$releasever/Modular/$basearch/" }
  - {
      path: "/etc/yum.repos.d/rpmfusion-free.repo",
      section: "rpmfusion-free",
      option: "baseurl",
      value: "{{ yum_repos_mirror }}/fedora/rpmfusion/free/fedora/releases/$releasever/Everything/$basearch/os/",
    }
  - {
      path: "/etc/yum.repos.d/rpmfusion-free-updates.repo",
      section: "rpmfusion-free-updates",
      option: "baseurl",
      value: "{{ yum_repos_mirror }}/fedora/rpmfusion/free/fedora/updates/$releasever/$basearch/",
    }

yum_repos_tweaks: "{{ yum_repos_tweaks_original }}"

#TODO:clean, deduplicate
# common packages for all groups
package_list__fedora:
  #- the_silver_searcher    # ag
  - awesome-vim-colorschemes
  - bat       # A cat(1) clone with wings. (Rust)
  - bcc
  - bind-utils
  - bpftrace
  - cargo
  - cockpit
  #- cockpit-machines
  #- cockpit-pcp
  #- cockpit-podman
  #- cockpit-selinux
  - colordiff
  - colorized-logs
  - crudini # A utility for manipulating ini files
  #- clide  # colorize ASCII text
  - curl
  - dnf-utils
  - dnstop
  #- exa
  - fd-find  # alternative to find
  - fzf  #A command-line fuzzy finder
  - git
  #- go-task
  - golang
  - htop
  - inotify-tools
  - jq
  - lm_sensors
  - mtr
  #- nethogs
  - nmap-ncat
  - openssl
  - parallel
  - perf
  - powerline
  - powertop
  - progress # Linux tool to show progress for cp, mv, dd, ... (formerly known as cv)
  - pv # monitor the progress of data through a pipe
  - python3-pip
  - python3-psutil
  #- python3-pytelegrambotapi
  #- ranger      # console file manager
  #- rdiff-backup
  - rsync
  - rust
  #- screen
  - smartmontools
  - sysstat
  - tmux
  - tmux-powerline
  - tuned
  - vim-enhanced
  - vim-nerdtree
  - vim-powerline
  - wget
  #- chisel  # fast TCP/UDP tunnel, transported over HTTP, secured via SSH
  #- proxychains-ng    # ProxyChains NG hooks network-related (TCP only) libc functions
  #- stunnel
