---
package_list__fedora_ham:
  - minicom
  - gqrx
  - flrig
  - fldigi
  - wsjtx
  - js8call
  - cwdaemon
  - unixcw   #cw, cwcp, cwgen
  - wfview
  #- freedv

flatpak_packages__fedora_ham:
  - io.github.foldynl.QLog
#  - org.wfview.wfview      # (rpm package instead)
#  - edu.princeton.physics.WSJTX

# dash/dock panel favorite apps ($ dconf read /org/gnome/shell/favorite-apps)
# dconf read /org/gnome/shell/favorite-apps
# in case there are other favorite_apps__ variables the __NN__ suffix controlls position, i.e.
# __00__ -  to be on the left side (start of the list)
# __99__ -  to be on the right side (end of the list)
favorite_apps__99__fedora_ham:
  - edu.princeton.physics.WSJTX.desktop
  - io.github.foldynl.QLog.desktop
