---
package_list__ham:
  - gqrx
  - flrig
  - fldigi
  - wsjtx
  - js8call
  - cwdaemon
  - unixcw
  - wfview

flatpak_packages__ham:
  - io.github.foldynl.QLog
#  - org.wfview.wfview      # (rpm package instead)
