# # add user to groups (after installing packages)
# user_name: goloshubov
# user_groups:
#   - libvirt
#   - docker

#third party repos
# copr_list:
#   - mroche/cloud-native-utilities      # helm,knative-client,pack,packer,tektoncd-cli,terraform
#   - varlad/helix

#third party repos
# other_repos_list:
#   - ""

#third party repos and packages
direct_package_list:
  - "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version }}.noarch.rpm"
#  - "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_version }}.noarch.rpm"

#third party repos and packages
#    prerequisite_packages_list:
#      - ""

# enable repo if needed
#    setenabled_repo_list:

# NOTE: already defined in group_vars/all.yml, re-define here to override
#    yum_repos_mirror:
#    yum_repos_tweaks:

#TODO:
#package_list__union__g_servers:

pip_list:
  - Jinja2
  - ansible
  #  - ansible-rulebook
  #  - ansible-runner
  #  - wheel
  #  - aiohttp   # required for ansible.eda plugins (event_source/webhook.py)
  - yq
  - kubernetes
  - powerline-k8s
