---

- name: print info
  hosts: all
  tasks:
    - debug:
        msg: "host: {{ inventory_hostname }} groups: {{ group_names }}  tags: {{ hostvars[inventory_hostname].ansible_run_tags }}"
      tags: always

- name: confirmation
  hosts: localhost
  vars_prompt:
    - name: confirmation
      prompt: continue (y/n)?
      private: false
  tasks:
    - name: check confirmation
      fail:
        msg: "not y/Y"
      when: confirmation != "y" and confirmation != "Y"
      tags: always


- name: workstations configuration
  import_playbook: workstation.yml

- name: servers configuration
  import_playbook: server.yml

...
