---
- name: print info
  hosts: all
  gather_facts: false
  tasks:
    - ansible.buiting.debug:
        msg: "host: {{ inventory_hostname }}; groups: {{ group_names }}; ansible_run_tags: {{ hostvars[inventory_hostname].ansible_run_tags }}"
      tags: always

- name: confirmation
  hosts: all
  gather_facts: false
  vars_prompt:
    - name: confirm_answer
      prompt: "run plays on correspoding hosts/groups above?\ncontinue (y/n)?"
      private: false
  tasks:
    - name: check confirmation
      fail:
        msg: "not y/Y"
      when: confirm_answer != "y" and confirm_answer != "Y"
      tags: always
      run_once: true
