---
- name: Dry-run notification
  hosts: all
  gather_facts: no
  tags: always
  tasks:
    - name: This task will be skipped in check mode
      ansible.buiting.debug:
        msg: "{{ ansible_check_mode | ternary('DRY RUN', 'NOT A DRY RUN') }}"
      run_once: true
