---

- name: Apply server configuration
  hosts: servers
  gather_facts: yes
  check_mode: "{{ lookup('ansible.builtin.env', 'ANSIBLE_DRY_RUN', default=dry_run|default('no')) }}"
  diff:       "{{ lookup('ansible.builtin.env', 'ANSIBLE_DRY_RUN', default=dry_run|default('no')) }}"
  roles:
    - dotfiles
    - union_vars  # merge package_list
    - packages
    - pip

...
