---
- name: Apply workstation configuration
  hosts: workstations
  gather_facts: true
  roles:
    - groupby
    - filesrepos
    - dotfiles
    - packages
    - groups
    - flatpaks
    - pip
    - pipx
    - cargo
    - go
    - ansible
    - gnome
