---

- name: Apply workstation configuration
  hosts: workstations
  gather_facts: yes
  check_mode: "{{ lookup('ansible.builtin.env', 'ANSIBLE_DRY_RUN', default=dry_run|default('no')) }}"
  diff:       "{{ lookup('ansible.builtin.env', 'ANSIBLE_DRY_RUN', default=dry_run|default('no')) }}"
  roles:
    - dotfiles
    - union_vars  # merge package_list
    - packages
    - groups
    - flatpaks
    - pip
    - cargo
    - go
    - ansible
    - gnome

...
