---


- hosts: workstations
  gather_facts: yes
  roles:
    - union_vars  # merge package_list
    - dotfiles
    - packages
    - groups
    - flatpaks
    - pip
    - cargo
    - go
    - ansible
    - gnome 


...
