---

- import_playbook: dry-run-note.yml

- name: Apply workstation configuration
  hosts: workstations
  gather_facts: yes
  check_mode: "{{ lookup('ansible.builtin.env', 'ANSIBLE_DRY_RUN', default=ansible_check_mode) }}"
  diff:       "{{ lookup('ansible.builtin.env', 'ANSIBLE_DRY_RUN', default=ansible_check_mode) }}"
  roles:
    - dotfiles
    - union_vars  # merge package_list
    - packages
    - groups
    - flatpaks
    - pip
    - cargo
    - go
    - ansible
    - gnome

...
