---

- name: Apply workstation configuration
  hosts: workstations
  gather_facts: no
  roles:
    - union_vars  # merge package_list
    - dotfiles
    - packages
    - groups
    - flatpaks
    - pip
    - cargo
    - go
    - ansible
    - gnome

...
