---
- name: Install packages
  ansible.builtin.package:
    state: latest
    name: "{{ package_list }}"
  when: package_list is defined

- name: Remove packages
  ansible.builtin.package:
    state: absent
    name: "{{ package_absent_list }}"
  when: package_absent_list is defined
