---
- name: RedHat packages tasks
  become: true
  block:
    - name: Merge vars
      tags:
        - up
        - pkg_up
      ansible.builtin.set_fact:
        "{{ item }}": "{{ lookup('community.general.merge_variables', item, pattern_type='prefix') }}"
      loop:
        - copr_list
        - copr_absent_list
        - other_repos_list
        - direct_package_list
        - prerequisite_packages_list
        - setenabled_repo_list
        - package_list
        - package_absent_list

    - name: Print vars
      tags:
        - up
        - pkg_up
      ansible.builtin.debug:
        msg: "{{ lookup('vars', item, default='') }}"
      loop:
        - copr_list
        - copr_absent_list
        - other_repos_list
        - direct_package_list
        - prerequisite_packages_list
        - setenabled_repo_list
        - package_list
        - package_absent_list

    - name: Enable copr repos
      tags:
        - pkg_repos
        - pkg_repos_copr
      community.general.copr:
        name: "{{ item }}"
        state: enabled
      loop: "{{ copr_list }}"
      when: copr_list is defined

    - name: Remove copr repos
      tags:
        - pkg_repos
        - pkg_repos_copr
      community.general.copr:
        name: "{{ item }}"
        state: absent
      loop: "{{ copr_absent_list }}"
      when: copr_absent_list is defined

    - name: Install other repos
      tags:
        - pkg_repos
      command: dnf config-manager --add-repo '{{ item }}' -y
      loop: "{{ other_repos_list }}"
      when: other_repos_list is defined

    - name: Install requirement for ansible dnf module
      command: dnf install python3-libdnf5 -y

    - name: Install packages (direct link)
      tags:
        - pkg_direct
        - pkg_repos
        - up
        - pkg_up
      ansible.builtin.dnf:
        state: latest
        name: "{{ direct_package_list }}"
        disable_gpg_check: true
      when: direct_package_list is defined

    - name: Install prerequisite packages (repos)
      tags:
        - pkg_repos
        - up
        - pkg_up
      ansible.builtin.dnf:
        state: latest
        name: "{{ prerequisite_packages_list }}"
      when: prerequisite_packages_list is defined

    - name: Enable repos
      tags: pkg_repos
      command: dnf config-manager --set-enabled "{{ item }}"
      loop: "{{ setenabled_repo_list }}"
      when: setenabled_repo_list is defined

    - name: Apply repo_tweaks. delete mutually exclusive value (metalink|baseurl)
      tags:
        - pkg_repos
        - pkg_repos_tweaks
      community.general.ini_file:
        path: "{{ item.path }}"
        section: "{{ item.section }}"
        option: '{{ (item.option == "baseurl") | ternary("metalink", "baseurl") }}'
        state: absent
        backup: true
        no_extra_spaces: true
      when: yum_repos_tweaks is defined and (item.option == "metalink" or item.option == "baseurl")
      loop: "{{ yum_repos_tweaks }}"

    - name: Apply repo_tweaks. set new value
      tags:
        - pkg_repos
        - pkg_repos_tweaks
      community.general.ini_file:
        path: "{{ item.path }}"
        section: "{{ item.section }}"
        option: "{{ item.option }}"
        value: "{{ item.value }}"
        backup: true
        no_extra_spaces: true
      loop: "{{ yum_repos_tweaks }}"
      when: yum_repos_tweaks is defined

    #- name: Packages
    #  ansible.builtin.import_tasks: packages.yml

    - name: Install packages
      tags:
        - up
        - pkg_up
      ansible.builtin.dnf:
        state: latest
        name: "{{ package_list }}"
      when: package_list is defined

    - name: Remove packages
      ansible.builtin.dnf:
        state: absent
        name: "{{ package_absent_list }}"
      when: package_absent_list is defined

    - name: Upgrade packages
      tags:
        - up_all
        - pkg_up_all
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_cache: true
        security: "{{ packages_upgrade_security_only | d(false) }}"
      when: packages_upgrade
