---


- block:
    - name: enable copr repos
      command: dnf copr enable '{{ item }}' -y
      loop:  "{{ copr_list }}"
      tags: software, package-repos
    
    - name: install other repos
      command: dnf config-manager --add-repo '{{ item }}' -y
      loop: "{{ other_repos_list }}"
      tags: package-repos
    
    - name: install packages (direct link)
      dnf:
        state: latest
        name: "{{ direct_package_list }}"
      tags: package-repos
    
    - name: install prerequisite packages (repos)
      dnf:
        state: latest
        name: "{{ prerequisite_packages_list }}"
      tags: [ software, package-repos, packages ]
    
    - name: enable repos
      command: dnf config-manager --set-enabled "{{ item }}"
      loop: "{{ setenabled_repo_list }}"
      tags: package-repos
   
    - debug:
        msg: "debug->  value == {{ lookup('ansible.builtin.ini', item.option, section=item.section, file=item.path) }}"
      loop: "{{ yum_repos_tweaks }}"
      tags: [ package-repos, package-repos-tweaks ]
      
    - name: repo_tweaks. delete mutually exclusive value (metalink|baseurl)
      community.general.ini_file:
        path: '{{ item.path }}'
        section: '{{ item.section }}'
        option: '{{ ( item.option == "baseurl" ) | ternary("metalink", "baseurl") }}'
        state: absent
        backup: true
        no_extra_spaces: true
      when: (item.option == "metalink" or item.option == "baseurl")
      loop: "{{ yum_repos_tweaks }}"
      tags: [ package-repos, package-repos-tweaks ]
    
    - name: repo_tweaks. set new value
      community.general.ini_file:
        path: '{{ item.path }}'
        section: '{{ item.section }}'
        option: '{{ item.option }}'
        value: '{{ item.value }}'
        backup: true
        no_extra_spaces: true
      loop: "{{ yum_repos_tweaks }}"
      tags: [ package-repos, package-repos-tweaks ]
    
    - name: install packages
      dnf:
        state: latest
        name: "{{ package_list }}"
 

  tags: [ software, packages ]
  become: true


...
