---

- name: Packages tasks
  tags: 
    - software
    - packages
  block:
    - name: Packages on RHEL-based OS
      import_tasks: redhat.yml
      when: |
        ansible_os_family == "RedHat"

    - name: Packets on Debian-based OS
      import_tasks: debian.yml
      when: |
        ansible_os_family == "Debian"

...
