---

- name: Packages tasks
  tags: 
    - software
    - packages
  become: true
  block:
    # we need import here (not include) to respect inner tags
    - import_tasks: redhat.yml
      when: ansible_os_family == "RedHat"

    - import_tasks: debian.yml
      when: ansible_os_family == "Debian"

...
