---

- name: Packages tasks
  tags: 
    - software
    - packages
  block:
    - name: Update packages on RHEL-based OS
      import_tasks: redhat.yml
      when: |
        ansible_os_family == "RedHat"

    - name: Update packets on Debian-based OS
      import_tasks: debian.yml
      when: |
        ansible_os_family == "Debian"

...
