---
- name: Ubuntu packages tasks
  become: true
  block:
    - name: Merge vars
      ansible.builtin.set_fact:
        "{{ item }}": "{{ lookup('community.general.merge_variables', item, pattern_type='prefix') }}"
      loop:
        #- other_repos_list
        #- direct_package_list
        #- prerequisite_packages_list
        - package_list
        - package_absent_list

    - name: Print vars
      ansible.builtin.debug:
        msg: "{{ lookup('vars', item, default='') }}"
      loop:
        #- other_repos_list
        #- direct_package_list
        #- prerequisite_packages_list
        - package_list
        - package_absent_list

    - name: Packages
      ansible.builtin.import_tasks: _packages.yml
