---

# byHostname/<hostname>/home dir
- name: check home dir (byHostname) 
  delegate_to: 127.0.0.1
  ansible.builtin.stat:
    path: "{{ item.localpath }}/byHostname/{{ ansible_facts['hostname'] }}/home/"
  register: host_homedir
- name: sync home dir (byHostname)
  synchronize:
    src: "{{ item.localpath }}/byHostname/{{ ansible_facts['hostname'] }}/home/"
    dest: ~/
  when: host_homedir.stat.islnk is defined
# byHostname/<hostname>/etc dir
- name: check etc dir (byHostname)
  delegate_to: 127.0.0.1
  ansible.builtin.stat:
    path: "{{ item.localpath }}/byHostname/{{ ansible_facts['hostname'] }}/etc/"
  register: host_etcdir
  tags: [ dotfiles, configs ]
- name: sync etc dir (byHostname)
  become: true
  synchronize:
    src: "{{ item.localpath }}/byHostname/{{ ansible_facts['hostname'] }}/etc/"
    dest: /etc/
    owner: false
    group: false
  when: host_etcdir.stat.islnk is defined

...
