---

# group/<group>/home/ dir
- name: Create directories. group (home dir)
  ansible.builtin.file:
    path: ~/{{ item.path }}
    state: directory
    #mode: '{{ item.mode }}'
  with_community.general.filetree: "{{ item[0].localpath }}/group/{{ item[1] }}/home/"
  when: item.state == 'directory'

- name: Instatiate j2 template. group (home dir)
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: ~/{{ item.path | regex_replace('\.j2$','') }}
    #mode: '{{ item.mode }}'
  with_community.general.filetree: "{{ item[0].localpath }}/group/{{ item[1] }}/home/"
  when: item.state == 'file' and item.path | regex_search('.j2$')

- name: Copy files. group (home dir)
  ansible.builtin.copy:
    src: '{{ item.src }}'
    dest: ~/{{ item.path }}
    #mode: '{{ item.mode }}'
  with_community.general.filetree: "{{ item[0].localpath }}/group/{{ item[1] }}/home/"
  when: item.state == 'file' and not item.path | regex_search('.j2$')


# group/<group>/etc/ dir
- name: Create directories. group (etc dir)
  become: true
  ansible.builtin.file:
    path: /etc/{{ item.path }}
    state: directory
    #mode: '{{ item.mode }}'
  with_community.general.filetree: "{{ item[0].localpath }}/group/{{ item[1] }}/etc/"
  when: item.state == 'directory'

- name: Instatiate j2 templates. group (etc dir)
  become: true
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: /etc/{{ item.path | regex_replace('\.j2$','') }}
    #mode: '{{ item.mode }}'
  with_community.general.filetree: "{{ item[0].localpath }}/group/{{ item[1] }}/etc/"
  #when: item.state == 'file'
  when: item.state == 'file' and item.path | regex_search('.j2$')

- name: Copy files. group (etc dir)
  become: true
  ansible.builtin.copy:
    src: '{{ item.src }}'
    dest: /etc/{{ item.path }}
    #mode: '{{ item.mode }}'
  with_community.general.filetree: "{{ item[0].localpath }}/group/{{ item[1] }}/etc/"
  #when: item.state == 'file'
  when: item.state == 'file' and not item.path | regex_search('.j2$')

...
