---
# group/<group>/home/ dir
- name: Create directories. group (home dir)
  become: yes
  become_user: "{{ user_name }}"
  ansible.builtin.file:
    path: ~/{{ item.path }}
    state: directory
    #mode: '{{ item.mode }}'
  with_community.general.filetree: "{{ item[0].localpath }}/group/{{ item[1] }}/home/"
  when: item.state == 'directory'

- name: Render j2 template. group (home dir)
  become: yes
  become_user: "{{ user_name }}"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: ~/{{ item.path | regex_replace('\.j2$','') }}
    #mode: '{{ item.mode }}'
  with_community.general.filetree: "{{ item[0].localpath }}/group/{{ item[1] }}/home/"
  when: item.state == 'file' and item.path | regex_search('.j2$')

- name: Copy files and links. group (home dir)
  become: yes
  become_user: "{{ user_name }}"
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: ~/{{ item.path }}
    #mode: '{{ item.mode }}'
    follow: true
  with_community.general.filetree: "{{ item[0].localpath }}/group/{{ item[1] }}/home/"
  when: (item.state == 'file' or item.state == 'link') and not item.path | regex_search('.j2$')

# group/<group>/etc/ dir
- name: Create directories. group (etc dir)
  become: true
  ansible.builtin.file:
    path: /etc/{{ item.path }}
    state: directory
    #mode: '{{ item.mode }}'
  with_community.general.filetree: "{{ item[0].localpath }}/group/{{ item[1] }}/etc/"
  when: item.state == 'directory'

- name: Render j2 templates. group (etc dir)
  become: true
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: /etc/{{ item.path | regex_replace('\.j2$','') }}
    #mode: '{{ item.mode }}'
  with_community.general.filetree: "{{ item[0].localpath }}/group/{{ item[1] }}/etc/"
  #when: item.state == 'file'
  when: item.state == 'file' and item.path | regex_search('.j2$')

- name: Copy files and links. group (etc dir)
  become: true
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: /etc/{{ item.path }}
    #mode: '{{ item.mode }}'
    follow: true
  with_community.general.filetree: "{{ item[0].localpath }}/group/{{ item[1] }}/etc/"
  when: (item.state == 'file' or item.state == 'link') and not item.path | regex_search('.j2$')
