---
# host/<hostname>/home/ dir
- name: Create directories. host (home dir)
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.file:
    path: ~/{{ item.path }}
    state: directory
    #mode: '{{ item.mode }}'
  with_community.general.filetree: "{{ item.localpath }}/host/{{ inventory_hostname }}/home/"
  when: item.state == 'directory'

- name: Render j2 templates. host (home dir)
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: ~/{{ item.path | regex_replace('\.j2$', '') }}
    #mode: '{{ item.mode }}'
  with_community.general.filetree: "{{ item.localpath }}/host/{{ inventory_hostname }}/home/"
  when: item.state == 'file' and item.path | regex_search('.j2$')

- name: Copy files. host (home dir)
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: ~/{{ item.path }}
    #mode: '{{ item.mode }}'
  with_community.general.filetree: "{{ item.localpath }}/host/{{ inventory_hostname }}/home/"
  when: item.state == 'file' and not item.path | regex_search('.j2$')

- name: Recreate links. host (home dir)
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: ~/{{ item.path }}
    state: link
    force: true
    #mode: '{{ item.mode }}'
  with_community.general.filetree: "{{ item.localpath }}/host/{{ inventory_hostname }}/home/"
  when: item.state == 'link'

# host/<hostname>/etc/ dir
- name: Create directories. host (etc dir)
  become: true
  ansible.builtin.file:
    path: /etc/{{ item.path }}
    state: directory
    #mode: '{{ item.mode }}'
  with_community.general.filetree: "{{ item.localpath }}/host/{{ inventory_hostname }}/etc/"
  when: item.state == 'directory'

- name: Render j2 templates. host (etc dir)
  become: true
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: /etc/{{ item.path | regex_replace('\.j2$', '') }}
    #mode: '{{ item.mode }}'
  with_community.general.filetree: "{{ item.localpath }}/host/{{ inventory_hostname }}/etc/"
  when: item.state == 'file' and item.path | regex_search('.j2$')

- name: Copy files. host (etc dir)
  become: true
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: /etc/{{ item.path }}
    #mode: '{{ item.mode }}'
  with_community.general.filetree: "{{ item.localpath }}/host/{{ inventory_hostname }}/etc/"
  when: item.state == 'file' and not item.path | regex_search('.j2$')

- name: Recreate links. host (etc dir)
  become: true
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: /etc/{{ item.path }}
    state: link
    force: true
    #mode: '{{ item.mode }}'
  with_community.general.filetree: "{{ item.localpath }}/host/{{ inventory_hostname }}/etc/"
  when: item.state == 'link'
