---

- name: The dotfiles role's tasks
  tags:
    - dotfiles
    - configs
  block:
    - name: Print vars
      debug:
        msg: "{{ lookup('vars', item, default='') }}"
      loop: "{{ print_vars }}"

    # group/<groupname>/{home,etc} dirs
    - name: Group specific configs
      include_tasks: group.yml
      # loop: "{{ files_repos | product (group_names) | list }}"    #the 'all' group isn't in the host's group_names, workaround:
      loop: "{{ files_repos | product ( ['all'] | union(group_names)) | list }}"

    # host/<hostname>/{home,etc} dirs
    - name: Host specific configs
      include_tasks: host.yml
      loop: "{{ files_repos }}"

...
