---

- block:
    - name: Get dotfiles
      delegate_to: 127.0.0.1
      git:
        repo: "{{ item.repo }}"
        dest: "{{ item.localpath }}"
        force: yes
        accept_hostkey: yes
      loop: "{{ files_repos }}"

    # group/<groupname>/{home,etc} dirs
    - name: Group specific configs
      include_tasks: group.yml
      # loop: "{{ files_repos | product (group_names) | list }}"    #the 'all' group isn't in the host's group_names, workaround:
      loop: "{{ files_repos | product ( ['all'] | union(group_names)) | list }}"

    # host/<hostname>/{home,etc} dirs
    - name: Host specific configs
      include_tasks: host.yml
      loop: "{{ files_repos }}"

  tags:
    - dotfiles
    - configs


...
