---

- block:
    - name: get dotfiles
      delegate_to: 127.0.0.1
      git:
        repo: "{{ item.repo }}"
        dest: "{{ item.localpath }}"
        force: yes
        accept_hostkey: yes
      loop: "{{ files_repos }}"
   

    # all/{home,etc} dirs
    - include_tasks: all.yml
      loop: "{{ files_repos }}"

    # byType/<type>/{home,etc} dirs
    - include_tasks: byType.yml
      loop: "{{ files_repos | product (type) | list }}"

    # byHostname/<hostname>/{home,etc} dirs
    - include_tasks: byHostname.yml
      loop: "{{ files_repos }}"

  tags: [ dotfiles, configs ]


...
