---

- name: get dotfiles
  git:
    repo: "{{ filesrepo }}"
    dest: "{{ filesdir }}"
    force: yes

- name: sync files
  synchronize:
    src: "{{ filesdir }}/files/"
    dest: ~/

- name: vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.vim/autoload/plug.vim

- name: install packages
  become: true
  package:
    state: latest
    name: "{{ package_list }}"

- name: add user to libvirt group
  become: yes
  shell: usermod -a -G libvirt '{{ansible_user}}'

#needs fedora-workstation-repositories installed first
- name: enable google-chrome repo
  become: yes
  shell: dnf config-manager --set-enabled google-chrome
- name: install google-chrome-stable
  become: true
  package:
    state: latest
    name:
      - google-chrome-stable

- name: add flathub remote (flatpak)
  become: yes
  shell: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

- name: install flatpaks
  flatpak:
    name: '{{ item }}'
    state: present
    remote: flathub
#    method: user
  loop: "{{ flatpak_list }}"

- name: set GNOME settings
  shell: '{{ item }}'
  loop:
    #GNOME
    - gsettings set org.gnome.desktop.background picture-uri 'file:///home/{{ ansible_user }}/Pictures/wallpapers/wallpaper.jpg'
    - gsettings set org.gnome.desktop.peripherals.mouse natural-scroll true
    - gsettings set org.gnome.desktop.peripherals.touchpad natural-scroll true
    - gsettings set org.gnome.desktop.peripherals.touchpad tap-to-click true
    - gsettings set org.gtk.Settings.FileChooser show-hidden true
    - gsettings set org.gnome.nautilus.preferences show-delete-permanently true
    - gsettings set org.gtk.Settings.FileChooser sort-directories-first true
    - gsettings set org.gnome.nautilus.icon-view default-zoom-level 'small'
    - gsettings set org.gnome.desktop.interface clock-show-weekday true
    - gsettings set org.gnome.desktop.interface show-battery-percentage true
    - gsettings set org.gnome.desktop.wm.preferences focus-mode 'sloppy'
    - gsettings set org.gnome.shell favorite-apps "['com.gexperts.Tilix.desktop', 'firefox.desktop', 'google-chrome.desktop', 'io.atom.Atom.desktop', 'org.gnome.gedit.desktop', 'com.getferdi.Ferdi.desktop', 'org.gnome.Nautilus.desktop', 'net.xmind.ZEN.desktop', 'org.gnome.Notes.desktop', 'com.github.gi_lom.dialect.desktop', 'org.gnome.Calculator.desktop', 'virt-manager.desktop', 'com.spotify.Client.desktop']"
    #Tilix
    - gsettings set com.gexperts.Tilix.Settings terminal-title-show-when-single false
    - gsettings set com.gexperts.Tilix.Settings terminal-title-style 'small'
    - gsettings set com.gexperts.Tilix.Settings theme-variant 'dark'
    - gsettings set com.gexperts.Tilix.Settings use-tabs true
    #TODO  set tilix color scheme
    #gedit
    - gsettings set org.gnome.gedit.preferences.editor scheme 'oblivion'
#- TODO apply settings / reload gnome shell (or smth)

...
