---

- name: get dotfiles
  git:
    repo: "{{ files_repo }}"
    dest: "{{ files_dir }}"
    force: yes

- name: sync files
  synchronize:
    src: "{{ files_dir }}/files/"
    dest: ~/

- name: vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.vim/autoload/plug.vim

- name: install packages
  become: true
  package:
    state: latest
    name: "{{ package_list }}"

- name: add user to libvirt group
  become: yes
  shell: usermod -a -G libvirt '{{ansible_user}}'

#needs fedora-workstation-repositories installed first
- name: enable google-chrome repo
  become: yes
  shell: dnf config-manager --set-enabled google-chrome
- name: install google-chrome-stable
  become: true
  package:
    state: latest
    name:
      - google-chrome-stable

- name: add flathub remote (flatpak)
  become: yes
  shell: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

- name: install flatpaks
  flatpak:
    name: '{{ item }}'
    state: present
    remote: flathub
#    method: user
  loop: "{{ flatpak_list }}"


- name: set GNOME settings
  dconf:
    key: '{{ item.key }}'
    value: '{{ item.value }}'
  loop:
    #GNOME
    - { key: "/org/gnome/desktop/background/picture-uri", value: "'file:///home/{{ ansible_user }}/Pictures/wallpapers/wallpaper.jpg'" }
    - { key: "/org/gnome/desktop/peripherals/mouse/natural-scroll", value: "true" }
    - { key: "/org/gnome/desktop/peripherals/touchpad/natural-scroll", value: "true" }
    - { key: "/org/gnome/desktop/peripherals/touchpad/tap-to-click", value: "true" }
    - { key: "/org/gtk/Settings/FileChooser/show-hidden", value: "true" }
    - { key: "/org/gnome/nautilus/preferences/show-delete-permanently", value: "true" }
    - { key: "/org/gtk/Settings/FileChooser/sort-directories-first", value: "true" }
    - { key: "/org/gnome/nautilus/icon-view/default-zoom-level", value: "'small'" }
    - { key: "/org/gnome/desktop/interface/clock-show-weekday", value: "true" }
    - { key: "/org/gnome/desktop/interface/show-battery-percentage", value: "true" }
    - { key: "/org/gnome/desktop/wm/preferences/focus-mode", value: "'sloppy'" }
    - { key: "/org/gnome/shell/favorite-apps", value: "{{ favorite_apps }}" }
    #Tilix
    - { key: "/com/gexperts/Tilix/Settingsterminal-title-show-when-single", value: "false" }
    - { key: "/com/gexperts/Tilix/Settingsterminal-title-style", value: "'small'" }
    - { key: "/com/gexperts/Tilix/Settingstheme-variant", value: "'dark'" }
    - { key: "/com/gexperts/Tilix/Settingsuse-tabs", value: "true" }
    #TODO  set tilix color scheme
    #gedit
    - { key: "/org/gnome/gedit/preferences/editor/scheme", value: "'oblivion'" }
##- TODO apply settings / reload gnome shell (or smth)

...
