---
- name: Install cargo packages
  tags:
    - software
    - cargo
  block:
    - name: Print vars
      debug:
        msg: "{{ lookup('vars', item, default='') }}"
      loop:
        - cargo_list

    - name: Install cargo packages
      community.general.cargo:
        state: latest
        name: "{{ cargo_list }}"
