---
- name: Install cargo packages
  tags:
    - software
    - cargo
  block:
    - name: Print vars
      ansible.buiting.debug:
        msg: "{{ lookup('vars', item, default='') }}"
      loop:
        - cargo_packages

    - name: Install cargo packages
      community.general.cargo:
        state: latest
        name: "{{ cargo_packages }}"
