---
- name: Install cargo packages
  tags:
    - software
    - cargo
  block:
    - name: Merge vars
      ansible.builtin.set_fact:
        "{{ item }}": "{{ lookup('community.general.merge_variables', item, pattern_type='prefix') }}"
      loop:
        - cargo_packages

    - name: Print vars
      ansible.builtin.debug:
        msg: "{{ lookup('vars', item, default='') }}"
      loop:
        - cargo_packages

    - name: Install cargo packages
      community.general.cargo:
        state: latest
        name: "{{ cargo_packages }}"
