---
- name: Install pip packages
  tags:
    - software
    - pip
  block:
    - name: Merge vars
      ansible.builtin.set_fact:
        "{{ item }}": "{{ lookup('community.general.merge_variables', item, pattern_type='prefix') }}"
      loop:
        - pip_packages

    - name: Print vars
      ansible.builtin.debug:
        msg: "{{ lookup('vars', item, default='') }}"
      loop:
        - pip_packages

    - name: Install pip packages
      ansible.builtin.pip:
        name: "{{ pip_packages }}"
