---
- name: Load dconf dump files
  become: yes
  become_user: "{{ user_name }}"
  become_method: machinectl
  ansible.builtin.shell: "dconf load -f  /{{ item.path | basename | regex_replace('__','/') }}/ < {{ item.path }}"
  loop: "{{ item.files }}"
