---

- name: Copy dumps to remote host
  become: yes
  become_user: "{{ user_name }}"
  ansible.builtin.copy:
    src: "{{ item.path }}"
    dest: "/tmp/{{ item.path | basename }}"
    #mode: '{{ item.mode }}'
  loop: "{{ item.files }}"

- name: Load dconf dump files
  become: yes
  become_user: "{{ user_name }}"
  environment:
    DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/{{ user_id }}/bus"
  ansible.builtin.shell: "dconf load -f  /{{ item.path | basename | regex_replace('__','/') }}/ < /tmp/{{ item.path | basename }}"
  loop: "{{ item.files }}"

- name: Remove dumps from remote host
  become: yes
  become_user: "{{ user_name }}"
  ansible.builtin.file:
    path: "/tmp/{{ item.path | basename }}"
    state: absent
  loop: "{{ item.files }}"
