---
- name: GNOME tasks
  tags:
    - configs
    - gnome
  block:
    - name: Print vars
      ansible.builtin.debug:
        msg: "{{ lookup('vars', item, default='') }}"
      loop:
        - dconf_settings

    - name: Find dconf dump files in 'group' dir
      ansible.builtin.find:
        paths: "{{ item[0].localpath }}/group/{{ item[1] }}/dconf/"
        file_type: file
      register: type_dconfdumps
      loop: "{{ files_repos | product(['all']|union(group_names)) | list }}"
    - name: Load dconf dumps, 'group' dir
      ansible.builtin.include_tasks: dconf.yml
      loop: "{{ type_dconfdumps.results }}"

    - name: Apply dconf key-value settings
      become: yes
      become_user: "{{ user_name }}"
      community.general.dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      loop: "{{ dconf_settings | dict2items }}"

    - name: Find dconf dump files in 'host' dir
      ansible.builtin.find:
        paths: "{{ item.localpath }}/host/{{ inventory_hostname }}/dconf/"
        file_type: file
      register: host_dconfdumps
      loop: "{{ files_repos }}"
    - name: Load dconf dumps, 'host' dir
      ansible.builtin.include_tasks: dconf.yml
      loop: "{{ host_dconfdumps.results }}"
