---

- block:
    - name: find dconf dump files in 'byGroup' dir
      ansible.builtin.find:
        paths: "{{ files_dir }}/byGroup/{{ type }}/dconf/"
        file_type: file
      register: type_dconfdumps
    - name: configure GNOME. Load dconf dumps, 'byGroup' dir
      shell: "dconf load -f  /{{ item.path | basename | regex_replace('__','/') }}/ <  {{ files_dir}}/byGroup/{{ type }}/dconf/{{ item.path | basename }}" 
      loop: "{{ type_dconfdumps.files }}"

    - name: find dconf dump files in 'byHostname' dir
      ansible.builtin.find:
        paths: "{{ files_dir }}/byHostname/{{ ansible_facts['hostname'] }}/dconf/"
        file_type: file
      register: host_dconfdumps
    - name: configure GNOME. Load dconf dumps, 'byHostname' dir
      shell: "dconf load -f  /{{ item.path | basename | regex_replace('__','/') }}/ <  {{ files_dir}}/byHostname/{{ ansible_facts['hostname'] }}/dconf/{{ item.path | basename }}" 
      loop: "{{ host_dconfdumps.files }}"
    
    
    - name: configure GNOME (dconf, inventory keys,values)
      dconf:
        key: '{{ item.key }}'
        value: '{{ item.value }}'    
      loop: "{{ lookup('ansible.builtin.dict', dconf_settings) }}"


  tags: [ configs, gnome ]


...
