---

- name: GNOME tasks
  tags:
    - configs
    - gnome
  block:
    - name: find dconf dump files in 'group' dir
      ansible.builtin.find:
        paths: "{{ files_dir }}/group/{{ type }}/dconf/"
        file_type: file
      register: type_dconfdumps
    - name: configure GNOME. Load dconf dumps, 'group' dir
      shell: "dconf load -f  /{{ item.path | basename | regex_replace('__','/') }}/ <  {{ files_dir}}/group/{{ type }}/dconf/{{ item.path | basename }}" 
      loop: "{{ type_dconfdumps.files }}"

    - name: find dconf dump files in 'host' dir
      ansible.builtin.find:
        paths: "{{ files_dir }}/host/{{ inventory_hostname }}/dconf/"
        file_type: file
      register: host_dconfdumps
    - name: configure GNOME. Load dconf dumps, 'host' dir
      shell: "dconf load -f  /{{ item.path | basename | regex_replace('__','/') }}/ <  {{ files_dir}}/host/{{ inventory_hostname }}/dconf/{{ item.path | basename }}" 
      loop: "{{ host_dconfdumps.files }}"


    - name: configure GNOME (dconf, inventory keys,values)
      dconf:
        key: '{{ item.key }}'
        value: '{{ item.value }}'    
      loop: "{{ lookup('ansible.builtin.dict', dconf_settings) }}"

...
