---

- name: GNOME tasks
  tags:
    - configs
    - gnome
  block:
    - name: Find dconf dump files in 'group' dir
      ansible.builtin.find:
        paths: "{{ item[0].localpath }}/group/{{ item[1] }}/dconf/"
        file_type: file
      register: type_dconfdumps
      loop: "{{ files_repos | product(group_names) | list }}"
    - name: Load dconf dumps, 'group' dir
      include_tasks: dconf.yml
      loop: "{{ type_dconfdumps.results }}"

    - name: Find dconf dump files in 'host' dir
      ansible.builtin.find:
        paths: "{{ item.localpath }}/host/{{ inventory_hostname }}/dconf/"
        file_type: file
      register: host_dconfdumps
      loop: "{{ files_repos }}"
    - name: Load dconf dumps, 'host' dir
      include_tasks: dconf.yml
      loop: "{{ host_dconfdumps.results }}"

    - name: Apply dconf  key-value settings
      dconf:
        key: '{{ item.key }}'
        value: '{{ item.value }}'    
      loop: "{{ lookup('ansible.builtin.dict', dconf_settings) }}"

...
