---

- name: The union_vars role's tasks
  tags:
    - software
    - packages
  block:
    - name: Check files exist
      stat:
        path: "union_vars/group/{{ item }}.yml"
      register: union_vars_group
      loop: "{{ ['all'] | union(group_names) }}"
      delegate_to: 127.0.0.1
    - name: Check files exist
      stat:
        path: "union_vars/host/{{ inventory_hostname }}.yml"
      register: union_vars_host
      delegate_to: 127.0.0.1
  
    - name: Include groups vars to merge specific vars (package_list)
      include_vars:
        file: "{{ item.stat.path }}"
        name: "{{ item.item }}"
      when: item.stat.exists
      loop: "{{ union_vars_group.results }}"
      delegate_to: 127.0.0.1
    - name: Include host vars to merge specific vars (package_list)
      include_vars:
        file: "union_vars/host/{{ inventory_hostname }}.yml"
        name: "{{ inventory_hostname }}"
      when: union_vars_host.stat.exists
      delegate_to: 127.0.0.1
  
    # package_list
    - name: Merge package_list (groups)
      set_fact:
        package_list: "{{ package_list | default([]) | union ( hostvars[inventory_hostname][item.item].package_list ) }}"
      when: item.stat.exists and hostvars[inventory_hostname][item.item].package_list is defined
      loop: "{{ union_vars_group.results }}"
    - name: Merge package_list (host)
      set_fact:
        package_list: "{{ package_list | default([]) | union( hostvars[inventory_hostname][inventory_hostname].package_list ) }}"
      when: union_vars_host.stat.exists and hostvars[inventory_hostname][inventory_hostname].package_list is defined

...
