---

- name: The union_vars role's tasks
  tags:
    - software
    - packages
  block:
    - name: Print vars
      debug:
        msg: "{{ item }}"
      loop: "{{ union_vars }}"

    - name: Merge union_vars (host)
      set_fact:
        "{{ item }}": "{{ lookup('vars',item,default=[]) | community.general.lists_union(hostvars[inventory_hostname][item+'__union__h_'+inventory_hostname] | default([])) }}"
      loop: "{{ union_vars }}"

    - name: Merge union_vars (groups)
      set_fact:
        "{{ item[0] }}": "{{ lookup('vars',item[0],default=[]) | community.general.lists_union(hostvars[inventory_hostname][item[0]+'__union__g_'+item[1]] | default([])) }}"
      loop: "{{ union_vars | product ( ['all'] | union(group_names) ) | list }}"

...
