---

- name: The union_vars role's tasks
  tags:
    - software
    - packages
  block:
    - name: Print vars
      debug:
        msg: "{{ item }}"
      loop: "{{ print_vars }}"

    #TODO: use union_vars with loop (avoi duplication)

    - name: Merge copr_list (host)
      set_fact:
        copr_list: "{{ copr_list | community.general.lists_union( hostvars[inventory_hostname]['copr_list__union__h_'+inventory_hostname ] | default([]) ) }}"
    - name: Merge copr_list (groups)
      set_fact:
        copr_list: "{{ copr_list | community.general.lists_union( hostvars[inventory_hostname]['copr_list__union__g_'+item ] | default([]) ) }}"
      loop: "{{ ['all'] | union(group_names) }}"

    - name: Merge package_list (host)
      set_fact:
        package_list: "{{ package_list | community.general.lists_union( hostvars[inventory_hostname]['package_list__union__h_'+inventory_hostname ] | default([]) ) }}"
    - name: Merge package_list (groups)
      set_fact:
        package_list: "{{ package_list | community.general.lists_union( hostvars[inventory_hostname]['package_list__union__g_'+item ] | default([]) ) }}"
      loop: "{{ ['all'] | union(group_names) }}"

...
