---


- block:
  - name: check files exist
    stat:
      path: "./union_vars/group/{{ item }}.yml"
    register: union_vars_group
    loop: "{{ ['all'] | union(group_names) }}"
  - name: check files exist
    stat:
      path: "union_vars/host/{{ inventory_hostname }}.yml"
    register: union_vars_host


  - name: include groups vars to merge specific vars (package_list)
    include_vars:
      file: "{{ item.stat.path }}"
      name: "{{ item.item }}"
    when: item.stat.exists  == True
    loop: "{{ union_vars_group.results }}"
  - name: include host vars to merge specific vars (package_list)
    include_vars:
      file: "union_vars/host/{{ inventory_hostname }}.yml"
      name: "{{ inventory_hostname }}"
    when: union_vars_host.stat.exists == True


  # package_list
  - name: merge package_list (groups)
    set_fact:
      package_list: "{{ package_list | default([]) | union ( hostvars[inventory_hostname][item.item].package_list ) }}"
    when: item.stat.exists == True and hostvars[inventory_hostname][item.item].package_list is defined
    loop: "{{ union_vars_group.results }}"
  - name: merge package_list (host)
    set_fact:
      package_list: "{{ package_list | default([]) | union( hostvars[inventory_hostname][inventory_hostname].package_list ) }}"
    when: union_vars_host.stat.exists == True and hostvars[inventory_hostname][inventory_hostname].package_list is defined

  tags:
    - sowtware
    - packages


...
