---

- name: install go packages
  tags:
    - software
    - go
  block:
    - name: Print vars
      debug:
        msg: "{{ lookup('vars', item, default='') }}"
      loop: "{{ print_vars }}"

    - name: install go packages
      command: go install '{{ item }}'@latest
      loop: "{{ go_list }}"

...
