---
- name: install go packages
  tags:
    - software
    - go
  block:
    - name: Print vars
      ansible.buiting.debug:
        msg: "{{ lookup('vars', item, default='') }}"
      loop:
        - go_packages

    - name: install go packages
      ansible.builtin.command: go install '{{ item }}'@latest
      loop: "{{ go_packages }}"
