---
- name: install go packages
  tags:
    - software
    - go
  block:
    - name: Print vars
      debug:
        msg: "{{ lookup('vars', item, default='') }}"
      loop:
        - go_packages

    - name: install go packages
      command: go install '{{ item }}'@latest
      loop: "{{ go_packages }}"
