---
- name: Install go packages
  tags:
    - software
    - go
  block:
    - name: Merge vars
      ansible.builtin.set_fact:
        "{{ item }}": "{{ lookup('community.general.merge_variables', item, pattern_type='prefix') }}"
      loop:
        - go_packages

    - name: Print vars
      ansible.builtin.debug:
        msg: "{{ lookup('vars', item, default='') }}"
      loop:
        - go_packages

    - name: Install go packages
      ansible.builtin.command: go install '{{ item }}'@latest
      loop: "{{ go_packages }}"
