---
- name: Install ansible-galaxy collections
  tags:
    - software
    - ansible
  block:
    - name: Print vars
      ansible.buiting.debug:
        msg: "{{ lookup('vars', item, default='') }}"
      loop:
        - ansible_galaxy_collections

    - name: Install ansible-galaxy collections
      community.general.ansible_galaxy_install:
        type: collection
        name: "{{ item }}"
      loop: "{{ ansible_galaxy_collections }}"
