---

- name: Install ansible-galaxy collections
  tags:
    - software
    - ansible
  block:
    - name: Print vars
      debug:
        msg: "{{ lookup('vars', item, default='') }}"
      loop: "{{ print_vars }}"

    - name: Install ansible-galaxy collections
      community.general.ansible_galaxy_install:
        type: collection
        name: '{{ item }}'
      loop: "{{ ansible_galaxy_collection_list }}"

...
