---


- name: install ansible-galaxy collections
  community.general.ansible_galaxy_install:
    type: collection
    name: '{{ item }}'
  loop: "{{ ansible_galaxy_collection_list }}"
  tags: [ software, ansible ]


...
