---
- name: Install ansible-galaxy collections
  tags:
    - software
    - ansible
  block:
    - name: Merge vars
      ansible.builtin.set_fact:
        "{{ item }}": "{{ lookup('community.general.merge_variables', item, pattern_type='prefix') }}"
      loop:
        - ansible_galaxy_collections

    - name: Print vars
      ansible.builtin.debug:
        msg: "{{ lookup('vars', item, default='') }}"
      loop:
        - ansible_galaxy_collections

    - name: Install ansible-galaxy collections
      environment:
        ANSIBLE_COLLECTIONS_PATH: '{{ ansible_galaxy_venv is defined | ternary(
          "{{ python_venv_dir }}/{{ ansible_galaxy_venv }}/lib/python{{ python_version }}/site-packages/ansible_collections", 
          "~/.local/lib/python{{ python_version }}/site-packages/ansible_collections"
        ) }}'
      community.general.ansible_galaxy_install:
        type: collection
        name: "{{ item }}"
      loop: "{{ ansible_galaxy_collections }}"
