---
- name: Add user to group
  tags:
    - groups
    - configs
  block:
    - name: Merge vars
      ansible.builtin.set_fact:
        "{{ item }}": "{{ lookup('community.general.merge_variables', item, pattern_type='prefix') }}"
      loop:
        - user_groups

    - name: Print vars
      ansible.builtin.debug:
        msg: "{{ lookup('vars', item, default='') }}"
      loop:
        - user_groups

    - name: Add user to group
      become: yes
      ansible.builtin.user:
        name: "{{ user_name }}"
        groups: "{{ user_groups }}"
        append: true
