---
- name: Add user to group
  tags:
    - groups
    - configs
  block:
    - name: Print vars
      ansible.builtin.debug
        msg: "{{ lookup('vars', item, default='') }}"
      loop:
        - user_groups

    - name: Add user to group
      become: yes
      ansible.builtin.user:
        name: "{{ user_name }}"
        groups: "{{ user_groups }}"
        append: true
