---
- name: Pull files repos
  tags:
    - dotfiles
    - configs
    - gnome
  block:
    - name: Print vars
      ansible.builtin.debug:
        msg: "{{ lookup('vars', item, default='') }}"
      loop:
        - files_repos

    - name: Create repos local dirs
      delegate_to: 127.0.0.1
      ansible.builtin.file:
        path: "{{ item.localpath }}"
        state: directory
      loop: "{{ files_repos }}"

    - name: Get dotfiles from git repos
      delegate_to: 127.0.0.1
      git:
        repo: "{{ item.repo }}"
        dest: "{{ item.localpath }}"
        force: yes
        accept_hostkey: yes
      loop: "{{ files_repos }}"
