---
- name: Flatpaks tasks
  tags:
    - flatpaks
    - software
  block:
    - name: Merge vars
      ansible.builtin.set_fact:
        "{{ item }}": "{{ lookup('community.general.merge_variables', item, pattern_type='prefix') }}"
      loop:
        - flatpak_repos
        - flatpak_packages

    - name: Print vars
      ansible.builtin.debug:
        msg: "{{ lookup('vars', item, default='') }}"
      loop:
        - flatpak_repos
        - flatpak_packages

    - name: Flathub remotes
      become: true
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: "{{ item }}"
      loop: "{{ flatpak_repos }}"
      ignore_errors: true

    #    # fix for fedora where the flathub repo is disabled and filtered by default.
    #    - name: Enable flathub remote
    #      become: true
    #      command: flatpak remote-modify --enable --no-filter flathub
    #      changed_when: False

    - name: Install flatpaks
      community.general.flatpak:
        name: "{{ item }}"
        state: present
        remote: flathub
      #    method: user
      loop: "{{ flatpak_packages }}"
