---

- name: Flatpaks tasks
  tags:
    - flatpaks
    - software
  block:
    - name: Flathub remotes
      become: yes
      flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: '{{ item }}'
      loop: "{{ flatpak_repos }}"
    
    # fix for fedora where the flathub repo is disabled and filtered by default.
    - name: Enable flathub remote
      become: yes
      command: flatpak remote-modify --enable --no-filter flathub
      changed_when: False
    
    - name: Install flatpaks
      flatpak:
        name: '{{ item }}'
        state: present
        remote: flathub
    #    method: user
      loop: "{{ flatpak_list }}"

...
