---

#  command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
#  command: flatpak remote-modify --enable --no-filter flathub
#  or just shell: "flatpak remote-modify --enable --no-filter flathub || flatpak remote-add flathub https://flathub.org/repo/flathub.flatpakrepo"
- name: flatpak. add flathub remote
  become: yes
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: '{{ item }}'
  loop: "{{ flatpak_repos }}"
  tags:
    - software
    - flatpak-repos

# fix for fedora where the flathub repo is disabled and filtered by default.
- name: flatpak. enable flathub remote
  become: yes
  command: flatpak remote-modify --enable --no-filter flathub
  tags:
    - software
    - flatpak-repos

- name: install flatpaks
  flatpak:
    name: '{{ item }}'
    state: present
    remote: flathub
#    method: user
  loop: "{{ flatpak_list }}"
  tags:
    - software
    - flatpaks


...
